new column name for points and make point only visible when entry is present
DatabayAG/AntragoGradeOverview pull request #2
Opened 2022-04-09 12:39 UTC by mglaubitz

2022-04-12 07:06 UTC, mjansenDatabay commented on src/AntragoGradeOverview.php
> +						}
Can you please fix the indentation here? The code style should be similar to the ILIAS core :-).

2022-04-12 09:10 UTC, mjansenDatabay requested changes
Please adjust the coding style.

2022-04-21 07:59 UTC, mglaubitz commented on src/AntragoGradeOverview.php
> +						}
I have fixed the indentation - hopefully ;)

2022-04-21 08:25 UTC, mjansenDatabay approved these changes

2022-04-21 08:25 UTC, merged